### ISSUE TITLE
Question Option: inverse: true

### ISSUE THREAD

**Issue by fkaminski** [rsanchez/postcss-colors-only#3]
Trying to set Option "inverse: true" seems to have no effect.
Installing https://github.com/postcss/postcss-cli and the plugin with the following "postcss.config.js":

```
module.exports = {
  plugins: [
    require('postcss-colors-only')({ withoutGrey: false, withoutMonochrome: false, inverse: true }),
   ]
}
```
and calling from a package.json script entry like:

`"build:colorTheme": "postcss input.css --no-map --output output.css `

**Comment by Oblongmana** [comment]
In case anyone else comes across this in the future - it looks like this project isn't being actively maintained, though does continue to work. The `inverse` functionality was never published to npm - however you can get around this by directly installing. If using `yarn` (and you should be able to use a similar syntax with `npm`), running the following will get you the inverse functionality.

```
yarn add rsanchez/postcss-colors-only#03e49a7e95419fcfcee718d80b26fdd99eb32153 --save
```

No magic here - it just points to that commit where the inverse functionality was merged. You could also fork the repo and link to your own. This will add the following to your package.json
```
"postcss-colors-only": "rsanchez/postcss-colors-only#03e49a7e95419fcfcee718d80b26fdd99eb32153",
```

Not sure on the interaction with the cli tool (either postcss-cli or https://github.com/rsanchez/css-color-extractor-cli), but hopefully this helps.

Only quirk/bug I immediately noticed was that the text-shadows in the file I was dealing with were still there (e.g. `text-shadow:0 1px 1px rgba(255,255,255,0.75);`), so keep an eye out for that. Looks pretty good otherwise though!
